title: OAuth 2.0 Server
tagline: PHP, meet OAuth
description: A standards compliant OAuth 2.0 server
google_analytics_tracking_id: UA-46050814-5
menu:
    Getting Started:
        Introduction: '/'
        Simple example: '/simple-example/'
        Installation: '/installation/'